### ISSUE TITLE
Error on initializing the code

### ISSUE THREAD

**Issue by IndividualCoder** [rayanalysis/panda3d-complexpbr#2]
The code written in the readme file gives this error:
Traceback (most recent call last):
  File "c:\Users\Lenovo\Mombie challenge edtion\ursina editor\Editor\ok.py", line 94, in <module>
    main().run()
    ^^^^^^
  File "c:\Users\Lenovo\Mombie challenge edtion\ursina editor\Editor\ok.py", line 18, in __init__
    complexpbr.apply_shader(self.render)
  File "c:\Users\Lenovo\Mombie challenge edtion\ursina editor\Editor\complexpbr\__init__.py", line 181, in apply_shader
    complexpbr_rig_init(node, intensity=intensity, lut_fill=lut_fill)
  File "c:\Users\Lenovo\Mombie challenge edtion\ursina editor\Editor\complexpbr\__init__.py", line 146, in complexpbr_rig_init
    node.set_shader(base.complexpbr_shader)
TypeError: NodePath.set_shader() argument 1 must be Shader, not NoneType

**Comment by rayanalysis** [comment]
I'll refer this issue to the following thread which seems to clear this up: https://discourse.panda3d.org/t/manual-on-renderpipeline/29631/11

Thanks for opening the issue.
